name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test 👷🏻
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js, pnpm, and Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@9 --activate

      - name: Restore pnpm Cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies 🧳
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Check Lint, Typecheck, and Format 💅🏻
        run: |
          pnpm lint &
          pnpm typecheck &
          pnpm format:check
        shell: bash

      - name: Run Build 🔨
        run: pnpm build
