name: Deploy Docker Images

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      api-changed: ${{ steps.filter.outputs.api }}
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4
      - name: Check for changes 🔍
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            api:
              - 'apps/api/**'
              - 'packages/**'
  api:
    needs: check-changes
    if: needs.check-changes.outputs.api-changed == 'true'
    name:  Build API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4

      - name: Build and push docker image 🚀
        uses: ./.github/actions/docker
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          image_name: tape-api
          tag_name: 'latest'
          docker_file: ./apps/api/Dockerfile
